export default class Constants {
  static readonly API_URL: string = "https://riordon.xyz/api"

  static readonly RADIUS_CARD: number = 15
  static readonly RADIUS_BUTTON: number = 18
  static readonly RADIUS_FULL: number = 50

  static readonly FONT_SIZE_TITLE: number = 20
  static readonly FONT_SIZE_SUBTITLE: number = 16
  static readonly FONT_SIZE_COMMON: number = 14
  static readonly FONT_SIZE_BAR: number = 11
  static readonly FONT_SIZE_SMALL: number = 12

  static readonly FONT_WEIGHT_BOLD: number = 700

  static readonly PADDING_EDGE: number = 16
  static readonly PADDING_INNER: number = 10

  static readonly SIZE_ICON_SMALL: number = 20
  static readonly SIZE_ICON_MEDIUM: number = 24
  static readonly SIZE_ICON_LARGE: number = 32
  static readonly SIZE_AVATAR: number = 44
  static readonly SIZE_AVATAR_LARGE: number = 72
}